### ISSUE TITLE
Do not load in Chrome

### ISSUE THREAD

**Issue by hughlv** [ibnzUK/next-chrome-starter#1]
```
Cannot load extension with file or directory name _next. Filenames starting with "_" are reserved for use by the system.
```

There will be such error when loading the extension with Developer Mode on.

The reason is the Chrome does not allow path includes `_`. Need to modify to other names without _. 

Another issue is the CSP. If you have event handlers in tsx file. By default these scripts wont be loaded for security reason. Not sure if you have solution or not.

**Comment by ibnzUK** [comment]
Make sure you run  "exp": "next build && next export",

This makes out dir and removes _ prefix
