### ISSUE TITLE
How to change pop up dimensions?

### ISSUE THREAD

**Issue by smartpage** [ibnzUK/next-chrome-starter#2]
Hi, how do I change the popup dimensions?

Another question, do I have to rebuild and update on every change?

Thank you

**Comment by ibnzUK** [comment]
Popup size can be changed with .comtainer size : 

https://github.com/ibnzUK/next-chrome-starter/blob/087584e1b007d6c3307ab569221334b1eb043410/styles/Pages.module.css#L3


You can run on localhost, just like any other next app. but when ready to test in Chrome need to rebuild and update in chrome.
